# Generated by Django 5.2.6 on 2026-02-01 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_post_content_text_alter_profile_age_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_collaborative',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('EPHEMERAL', 'Ephemeral (24h)'), ('PERSISTENT', 'Persistent (stays on profile)')], default='EPHEMERAL', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
