# Generated by Django 5.2.6 on 2026-02-04 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_chatmessage_image_chatmessage_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationroom',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='locationroom',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
