# Generated by Django 5.2.6 on 2026-02-14 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_comment_likes_comment_parent_post_thumbnail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='connections_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='posts_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='social_gravity',
            field=models.FloatField(default=1.0),
        ),
    ]
