# Generated by Django 5.2.6 on 2026-02-14 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_profile_connections_count_profile_posts_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streak',
            name='last_post_date',
            field=models.DateField(),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['sender', 'receiver', '-timestamp'], name='core_chatme_sender__c121e5_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['receiver', 'is_read'], name='core_chatme_receive_ede677_idx'),
        ),
        migrations.AddIndex(
            model_name='connection',
            index=models.Index(fields=['sender', 'status'], name='core_connec_sender__0046a3_idx'),
        ),
        migrations.AddIndex(
            model_name='connection',
            index=models.Index(fields=['receiver', 'status'], name='core_connec_receive_188767_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-created_at'], name='core_post_created_84f629_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['expires_at'], name='core_post_expires_a4fcf0_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author', '-created_at'], name='core_post_author__dc61ce_idx'),
        ),
    ]
