# Generated by Django 5.2.6 on 2026-02-14 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_streak_last_post_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='chat_thumbnails/'),
        ),
        migrations.AddField(
            model_name='recoveryrequest',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
